import { Employee } from "./employees";

export const EMPLOYEES: Employee[] = [
  // TLs
  {
    id: "4",
    name: "David Brown",
    contractHours: 30,
    unavailableDates: [
      { day: 5, timeFrame: { start: "06:00", end: "14:00" } },
      { day: 4, timeFrame: { start: "06:00", end: "14:00" } },
    ],
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "TL",
    isBaker: false,
  },
  {
    id: "2",
    name: "Bob Lance",
    contractHours: 30,
    unavailableDates: [
      { day: 1, timeFrame: { start: "14:00", end: "22:00" } },
      { day: 2, timeFrame: { start: "14:00", end: "22:00" } },
      { day: 3, timeFrame: { start: "14:00", end: "22:00" } },
    ],
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    isBaker: false,
    role: "TL",
  },
  {
    id: "3",
    name: "Charlie Young",
    contractHours: 30,
    unavailableDates: [{ day: 3, timeFrame: { start: "06:00", end: "22:00" } }],
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    isBaker: false,
    role: "TL",
  },
  {
    id: "1",
    name: "Alice Bed",
    contractHours: 30,
    unavailableDates: [
      { day: 0, timeFrame: { start: "06:00", end: "14:00" } },
      { day: 2, timeFrame: { start: "14:00", end: "22:00" } },
    ],
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    isBaker: false,
    role: "TL",
  },

  // CTMs
  {
    id: "ctm-1",
    name: "Alice Green",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: false,
    unavailableDates: [{ day: 1, timeFrame: { start: "14:00", end: "22:00" } }],
  },
  {
    id: "ctm-2",
    name: "Ben Carter",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: true,
    unavailableDates: [],
  },
  {
    id: "ctm-3",
    name: "Cara Lewis",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: true,
    unavailableDates: [{ day: 3, timeFrame: { start: "06:00", end: "14:00" } }],
  },
  {
    id: "ctm-4",
    name: "Dan Foster",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: true,
    unavailableDates: [],
  },
  {
    id: "ctm-5",
    name: "Eva White",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: true,
    unavailableDates: [{ day: 4, timeFrame: { start: "06:00", end: "14:00" } }],
  },
  {
    id: "ctm-6",
    name: "Frank Hill",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: false,
    unavailableDates: [],
  },
  {
    id: "ctm-7",
    name: "Grace Moore",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: true,
    unavailableDates: [
      { day: 2, timeFrame: { start: "14:00", end: "22:00" } },
      { day: 2, timeFrame: { start: "06:00", end: "10:00" } },
    ],
  },
  {
    id: "ctm-8",
    name: "Harry Reed",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: false,
    unavailableDates: [],
  },
  {
    id: "ctm-9",
    name: "Isla Ford",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: false,
    unavailableDates: [{ day: 0, timeFrame: { start: "14:00", end: "22:00" } }],
  },
  {
    id: "ctm-10",
    name: "Jake Dean",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: true,
    unavailableDates: [],
  },
  {
    id: "ctm-11",
    name: "Kate Bell",
    contractHours: 16,
    totalWorkedHours: 0,
    assignedShifts: [],
    lastShiftEndTime: null,
    role: "CTM",
    isBaker: false,
    unavailableDates: [{ day: 6, timeFrame: { start: "06:00", end: "14:00" } }],
  },
];

export const COLORS = [
  "bg-amber-500",
  "bg-orange-500",
  "bg-yellow-500",
  "bg-green-500",
  "bg-teal-500",
  "bg-blue-500",
  "bg-indigo-500",
  "bg-purple-500",
  "bg-pink-500",
  "bg-gray-500",
  "bg-lime-500",
  "bg-amber-300",
  "bg-orange-300",
  "bg-yellow-300",
  "bg-green-300",
  "bg-teal-300",
  "bg-blue-300",
  "bg-lime-300",
  "bg-green-700",
  "bg-teal-700",
  "bg-blue-700",
  "bg-lime-700",
  "bg-amber-700",
  "bg-rose-500",
  "bg-cyan-500",
  "bg-violet-500",
  "bg-fuchsia-500",
  "bg-emerald-500",
  "bg-sky-500",
];

export const ACCENT_COLORS = [
  "accent-amber-500",
  "accent-orange-500",
  "accent-yellow-500",
  "accent-green-500",
  "accent-teal-500",
  "accent-blue-500",
  "accent-indigo-500",
  "accent-purple-500",
  "accent-pink-500",
  "accent-gray-500",
  "accent-lime-500",
  "accent-amber-300",
  "accent-orange-300",
  "accent-yellow-300",
  "accent-green-300",
  "accent-teal-300",
  "accent-blue-300",
  "accent-lime-300",
  "accent-green-700",
  "accent-teal-700",
  "accent-blue-700",
  "accent-lime-700",
  "accent-amber-700",
  "accent-rose-500",
  "accent-cyan-500",
  "accent-violet-500",
  "accent-fuchsia-500",
  "accent-emerald-500",
  "accent-sky-500",
];

export const UNASINGNED_BG_COLOR_BY_ROLE = {
  BAKER: "bg-gradient-to-r from-orange-500 via-amber-500 to-yellow-500",
  CTM: "bg-gradient-to-r from-emerald-500 via-lime-500 to-sky-500",
  TL: "bg-gradient-to-r from-cyan-500 via-blue-500 to-violet-500",
};

export const EMOJI_BY_ROLE = {
  BAKER: "🥐",
  CTM: "💁‍♀️",
  TL: "👑 ",
};
